name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: self-hosted
    steps:
      - run: docker login registry.fibo.cloud -p ${{ DOCKER_PASSWORD }} -u ${{ DOCKER_USERNAME }}
      - run: docker pull registry.fibo.cloud/darkhaa/test
     
